### ISSUE TITLE
[ic-hero] styling not applied when adding components into slot 

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-ui-kit#167] opened 2022-12-14 11:50 UTC
## Summary of the bug
On the component on the 'right-content' slot ICDSv2 styling is not being applied (This is only when components are put inside this slot rather than use a string)

## 🪜 How to reproduce
On the 'right-content' slot the default text styling is not being applied to content inside the IcCard which has been placed into the slot. However when it is placed into another slot such as the 'subheading', styling is being properly applied.

## 🧐 Expected behaviour
Styling should be applied even when components are put inside a slot

**Comment by gd2910** [comment] 2023-02-22 13:25
Unable to reproduce, fixed in a previous ticket.

**Closed by gd2910** 2023-02-22 13:25 UTC
Labels: type: bug 🐛, component: ic-hero
