### ISSUE TITLE
XS Left-hand nav does not include any keyboard navigation

### ISSUE THREAD

**Issue by fbd399** [mi6/ic-ui-kit#542] opened 2023-03-31 16:11 UTC
## Summary of the bug
When the left-hand nav component is open on small width devices, keyboard navigation is not set, so users are not able to navigate to any page

## 🪜 How to reproduce
Reduce screen size so left-hand nav appears as XS variant. Tab to component. Press 'space' to open. Notice how arrows or tabs do not move focus between pages.

## 🧐 Expected behaviour
Up/Down keys should move focus between pages, like select.

**Comment by ASM995** [comment] 2023-04-17 16:12
Closing as duplicate ticket.

**Comment by ad9242** [comment] 2023-05-04 09:09
duplicate of: https://github.com/mi6/ic-design-system/issues/421
fixed by https://github.com/mi6/ic-design-system/pull/435

**Closed by ad9242** 2023-05-04 09:09 UTC
Labels: navigation-item component
