### ISSUE TITLE
[ic-side-navigation]: Labels and icons disappear when switching between an open mobile, desktop then mobile variant. 

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#886] opened 2023-07-12 15:02 UTC
## Summary of the bug
The menu icons and labels disappear when switching between an open navigation menu to desktop to mobile. This may be due to the styling set within the `resizeObserver`. 

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Go to page: https://mi6.github.io/ic-ui-kit/branches/develop/?path=/story/web-components-side-navigation--default-story
2. Using the 'Default' story, set the browser size to mobile. Open the side navigation and leave open while increasing the browser screen to medium and then back to mobile.
4. See the error

## 🧐 Expected behaviour
The mobile variant should be showing the icons and labels for each menu item. 

## 📸 Screenshots or code
![Capture](https://github.com/mi6/ic-ui-kit/assets/116016939/4ec012d8-2552-4cf6-8525-30e1a406a58a)

## 🖥 Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 114

## 📱 Mobile
N/A

## Additional info
N/A

**Comment by GCHQ-Developer-847** [comment] 2023-07-17 19:58
Duplicate of #739

**Closed by GCHQ-Developer-847** 2023-07-17 19:58 UTC
Labels: type: bug 🐛, side-navigation component
